### ISSUE TITLE
Invalid path

### ISSUE THREAD

**Issue by JoergEm** [talkpython/nlp-with-python-and-spacy-course#1]
error: invalid path 'transcripts/356-ml-startups?dl=1_paragraphs.json
fatal: unable to checkout working tree

**Comment by koaning** [comment]
Could you elaborate? In particular, where does this issue arise? What lesson/notebook?

**Comment by JoergEm** [comment]
git clone

Had to download the zip like a noob.

**Comment by mikeckennedy** [comment]
Sorry for the trouble @JoergEm  FWIW I just tested a clone on macOS and Ubuntu and it seemed OK. I can't tested on my windows machine since it's all the way in the office across the way and it's a bit comfy on the couch. I wonder if there is an issue with your git install? Maybe see if there is an update and that could fix it? What OS and git version are you on?
